global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  # Publishes the dashboard insecurely on 8080 (just for testing)
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443