services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    #ports:
    #  - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - ./images:/app/public/images
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 'homepage.blackbox.lab.p-exe.com' # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage-http.rule=Host(`homepage.blackbox.lab.p-exe.com`)
      - traefik.http.routers.homepage-http.entrypoints=web
      #- traefik.http.services.gitlab-service.loadbalancer.server.port=3000
networks:
  traefik:
    external: true