services:
  gitlab:
    image: gitlab/gitlab-ce:18.7.1-ce.0
    container_name: gitlab
    shm_size: '256m'
    restart: unless-stopped
    #ports:
    #  - '80:80'
    #  - '443:443'
    #  - '22:22'
    volumes:
      - ./gitlab.rb:/etc/gitlab/gitlab.rb:ro
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab-http.rule=Host(`gitlab.blackbox.lab.p-exe.com`)
      - traefik.http.routers.gitlab-http.entrypoints=web
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab-http.service.loadbalancer.server.port=80

      #- traefik.http.routers.gitlab-registry.rule=Host(`gitlab-registry.blackbox.lab.p-exe.com`)
      #- traefik.http.routers.gitlab-registry.entrypoints=web
      - traefik.docker.network=traefik
      #- traefik.http.routers.gitlab-http.tls=true
      #- traefik.http.routers.gitlab-https.tls.certresolver=cloudflare
      
networks:
  traefik:
    external: true